services:
    alexdw_trumbowyg.form.type:
        class: "%alexdw_trumbowyg.form.type.class%"
        arguments: ["@service_container"]
        tags:
            - { name: form.type }
    alexdw_trumbowyg.twig_extension:
            class: Alexdw\TrumbowygBundle\Twig\TrumbowygExtension
            arguments: ["@service_container"]
            public: false
            tags:
                - { name: twig.extension }